export const categories = [
  { id: 1, name: "Apparel", icon: "👕" },
  { id: 2, name: "T-Shirts", icon: "👔" },
  { id: 3, name: "Accessories", icon: "💎" },
  { id: 4, name: "Jackets", icon: "🧥" },
  { id: 5, name: "Shirts", icon: "👗" },
  { id: 6, name: "New Arrivals", icon: "✨" },
  { id: 7, name: "Sale", icon: "🏷️" },
  { id: 8, name: "Collections", icon: "👥" },
]

export const products = [
  {
    id: 1,
    name: "The Girls Club T-Shirt - Blue",
    description:
      "Comfortable cotton t-shirt featuring 'The Girls Club' design with butterfly accent. Perfect for casual wear and showing your club spirit.",
    price: 29.99,
    originalPrice: 39.99,
    category: "Apparel",
    imageUrl: "/images/girls-club-blue.jpg",
    rating: 4.8,
    reviews: 247,
    stock: 45,
    variants: ["Blue", "Black", "Teal", "Red"],
  },
  {
    id: 2,
    name: "The Girls Club T-Shirt - Black",
    description:
      "Classic black t-shirt with 'The Girls Club' typography and butterfly logo. Versatile and stylish for any occasion.",
    price: 29.99,
    category: "Apparel",
    imageUrl: "/images/girls-club-black.jpg",
    rating: 4.9,
    reviews: 189,
    stock: 38,
    variants: ["Black", "Blue", "Teal", "Red"],
  },
  {
    id: 3,
    name: "The Girls Club T-Shirt - Teal",
    description:
      "Trendy teal colored t-shirt with premium 'The Girls Club' branding. Soft fabric blend for ultimate comfort.",
    price: 29.99,
    category: "Apparel",
    imageUrl: "/images/girls-club-teal.jpg",
    rating: 4.7,
    reviews: 156,
    stock: 42,
    variants: ["Teal", "Blue", "Black", "Red"],
  },
  {
    id: 4,
    name: "The Girls Club T-Shirt - Red",
    description:
      "Bold red t-shirt featuring 'The Girls Club' design. Make a statement with this vibrant and comfortable tee.",
    price: 29.99,
    category: "Apparel",
    imageUrl: "/images/girls-club-red.jpg",
    rating: 4.6,
    reviews: 203,
    stock: 35,
    variants: ["Red", "Blue", "Black", "Teal"],
  },
  {
    id: 5,
    name: "Dreamcatcher T-Shirt - White",
    description:
      "Beautiful white t-shirt with colorful dreamcatcher design on the back. Artistic and meaningful design for free spirits.",
    price: 34.99,
    originalPrice: 44.99,
    category: "Apparel",
    imageUrl: "/images/dreamcatcher-back.jpg",
    rating: 4.9,
    reviews: 178,
    stock: 28,
  },
  {
    id: 6,
    name: "Floral Border T-Shirt - White",
    description:
      "Elegant white t-shirt with decorative teal floral border pattern. Perfect for those who love subtle, artistic designs.",
    price: 32.99,
    category: "Apparel",
    imageUrl: "/images/floral-border-white.jpg",
    rating: 4.5,
    reviews: 134,
    stock: 41,
  },
  {
    id: 7,
    name: "Premium Pearl Necklace Set",
    description:
      "Elegant layered pearl necklace set as featured in our lifestyle collection. Perfect accessory for any outfit.",
    price: 89.99,
    category: "Accessories",
    imageUrl: "/images/lifestyle-pearls.jpg",
    rating: 4.8,
    reviews: 95,
    stock: 24,
  },
  {
    id: 8,
    name: "Vintage Plaid Shirt - Teal",
    description:
      "Retro-inspired plaid shirt in beautiful teal and pink tones. Comfortable fit with a vintage aesthetic.",
    price: 49.99,
    category: "Apparel",
    imageUrl: "/images/lifestyle-group.jpg",
    rating: 4.7,
    reviews: 87,
    stock: 19,
  },
  {
    id: 9,
    name: "Patterned Denim Jacket",
    description: "Unique denim jacket with artistic back panel design. Stand out piece for your wardrobe collection.",
    price: 79.99,
    category: "Apparel",
    imageUrl: "/images/lifestyle-group.jpg",
    rating: 4.6,
    reviews: 112,
    stock: 15,
  },
  {
    id: 10,
    name: "Floral Print Shirt - Brown",
    description: "Sophisticated floral print shirt in earthy brown tones. Perfect for casual or semi-formal occasions.",
    price: 44.99,
    category: "Apparel",
    imageUrl: "/images/lifestyle-group.jpg",
    rating: 4.4,
    reviews: 76,
    stock: 22,
  },
]

export const featuredProducts = products.slice(0, 4)
